### ISSUE TITLE
Megaman Battle Network 5 Team Protoman crashes (possibly reading from BIOS region)

### ISSUE THREAD

**Issue by gdkchan** [fredericmeyer/nanoboyadvance#19]
How to reproduce:
Start the game, after the intro scene Lan is called by his mother, and then MegaMan will ask you to look the Email. Enter on the menu (Start), open the Email menu (A). After a few seconds (usually something around 5 seconds) the emulator crashes.

I already saw this problem before and it's related to reading the BIOS region iirc. It should return the last opcode fetched from inside the bios region. If the wrong values are returned the game may crash. If you return the wrong value (like the value on that address) it crashes after some time. If you return zero it crashes right away.

You can see better explanation about how it works on GBATek, just search for "Reading from BIOS Memory".

**Comment by fredericmeyer** [comment]
Thanks for the report, once again! :)
I'm well aware of the open bus behaviour, it just has to be implemented.

**Comment by fredericmeyer** [comment]
Finally implemented / fixed :)
