### ISSUE TITLE
CMake doesn't work.

### ISSUE THREAD

**Issue by dpoole1337** [fredericmeyer/nanoboyadvance#28]
Please inform me if I'm messing up, but FindQt5Gui.cmake is missing.

`CMake Error at CMakeLists.txt:24 (find_package):
  By not providing "FindQt5Gui.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Gui", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt5Gui" with any
  of the following names:

    Qt5GuiConfig.cmake
    qt5gui-config.cmake

  Add the installation prefix of "Qt5Gui" to CMAKE_PREFIX_PATH or set
  "Qt5Gui_DIR" to a directory containing one of the above files.  If "Qt5Gui"
  provides a separate development package or SDK, be sure it has been
  installed.`

**Comment by fredericmeyer** [comment]
Hi this is not a bug.

You need to supply CMake with the path to Qt5Gui, Qt5OpenGL etc..
Pull the latest version of the code (I fixed an actual build bug on Windows/MinGW) and setup your CMake environment like this:
https://stackoverflow.com/a/27564751
                         
Let me know if it works!

Kind Regards,
Frederic

**Comment by dpoole1337** [comment]
Ah okay. Understood.
